var annotated_dup =
[
    [ "xmlnode", null, [
      [ "CXmlNode", "classxmlnode_1_1_c_xml_node.html", "classxmlnode_1_1_c_xml_node" ]
    ] ],
    [ "CAboutDlg", "class_c_about_dlg.html", "class_c_about_dlg" ],
    [ "CActor", "class_c_actor.html", "class_c_actor" ],
    [ "CActorFactory", "class_c_actor_factory.html", "class_c_actor_factory" ],
    [ "CAnimChannel", "class_c_anim_channel.html", "class_c_anim_channel" ],
    [ "CAnimChannelAngle", "class_c_anim_channel_angle.html", "class_c_anim_channel_angle" ],
    [ "CAnimChannelPoint", "class_c_anim_channel_point.html", "class_c_anim_channel_point" ],
    [ "CBasket", "class_c_basket.html", "class_c_basket" ],
    [ "CBasketActual", "class_c_basket_actual.html", "class_c_basket_actual" ],
    [ "CBasketAdapter", "class_c_basket_adapter.html", "class_c_basket_adapter" ],
    [ "CBasketStandin", "class_c_basket_standin.html", "class_c_basket_standin" ],
    [ "CCanadianExperienceApp", "class_c_canadian_experience_app.html", "class_c_canadian_experience_app" ],
    [ "CDrawable", "class_c_drawable.html", "class_c_drawable" ],
    [ "CFruit", "class_c_fruit.html", "class_c_fruit" ],
    [ "CFruitActual", "class_c_fruit_actual.html", "class_c_fruit_actual" ],
    [ "CFruitVisitor", "class_c_fruit_visitor.html", "class_c_fruit_visitor" ],
    [ "CGrowable", "class_c_growable.html", "class_c_growable" ],
    [ "CGrowableVisitor", "class_c_growable_visitor.html", "class_c_growable_visitor" ],
    [ "CHaroldFactory", "class_c_harold_factory.html", "class_c_harold_factory" ],
    [ "CHeadTop", "class_c_head_top.html", "class_c_head_top" ],
    [ "CImageDrawable", "class_c_image_drawable.html", "class_c_image_drawable" ],
    [ "CImageGrowable", "class_c_image_growable.html", "class_c_image_growable" ],
    [ "CLeaf", "class_c_leaf.html", "class_c_leaf" ],
    [ "CLimb", "class_c_limb.html", "class_c_limb" ],
    [ "CPicture", "class_c_picture.html", "class_c_picture" ],
    [ "CPictureFactory", "class_c_picture_factory.html", "class_c_picture_factory" ],
    [ "CPictureObserver", "class_c_picture_observer.html", "class_c_picture_observer" ],
    [ "CPolyDrawable", "class_c_poly_drawable.html", "class_c_poly_drawable" ],
    [ "CPropFactory", "class_c_prop_factory.html", "class_c_prop_factory" ],
    [ "CPseudoRandom", "class_c_pseudo_random.html", "class_c_pseudo_random" ],
    [ "CRotatedBitmap", "class_c_rotated_bitmap.html", "class_c_rotated_bitmap" ],
    [ "CSpartyFactory", "class_c_sparty_factory.html", "class_c_sparty_factory" ],
    [ "CStartAndHarvestDlg", "class_c_start_and_harvest_dlg.html", "class_c_start_and_harvest_dlg" ],
    [ "CTimeline", "class_c_timeline.html", "class_c_timeline" ],
    [ "CTimelineDlg", "class_c_timeline_dlg.html", "class_c_timeline_dlg" ],
    [ "CTree", "class_c_tree.html", "class_c_tree" ],
    [ "CTreeActorFactory", "class_c_tree_actor_factory.html", "class_c_tree_actor_factory" ],
    [ "CTreeActual", "class_c_tree_actual.html", "class_c_tree_actual" ],
    [ "CTreeAdapter", "class_c_tree_adapter.html", "class_c_tree_adapter" ],
    [ "CTreeDemoDlg", "class_c_tree_demo_dlg.html", "class_c_tree_demo_dlg" ],
    [ "CTreeDemoView", "class_c_tree_demo_view.html", "class_c_tree_demo_view" ],
    [ "CTreeFactory", "class_c_tree_factory.html", "class_c_tree_factory" ],
    [ "CTreeLibApp", "class_c_tree_lib_app.html", "class_c_tree_lib_app" ],
    [ "CTreeSeedDlg", "class_c_tree_seed_dlg.html", "class_c_tree_seed_dlg" ],
    [ "CTreeStandin", "class_c_tree_standin.html", "class_c_tree_standin" ],
    [ "CViewEdit", "class_c_view_edit.html", "class_c_view_edit" ],
    [ "CViewTimeline", "class_c_view_timeline.html", "class_c_view_timeline" ]
];